---

- name: Generate nginx configuration file
  template:
    src: http_server.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644

- block:
  - name: Check if nginx has already been configured for port {{http_server_port}}
    shell:
      semanage port -l | grep http_port_t | grep {{http_server_port}} | wc -l
    register: _http_ports

  - name: Allow nginx to listen on non-standard port (SELinux)
    shell: |
      semanage port -a -t http_port_t -p tcp {{http_server_port}}
    when: _http_ports.stdout == "0"
  when: ansible_selinux.status=='enabled'

- name: Start nginx
  service:
    name: nginx
    enabled: yes
    state: restarted
