---
# - debug:
#     var: groups

# - debug:
#     msg: "{{item}}: {{ hostvars[item].host }}"
#   with_items:
#     - "{{ groups['masters'] }}"
#     - "{{ groups['workers'] }}"

# - fail:

- name: Create NetworkManager key file
  template:
    src: ocp_customize_iso_nm.j2
    dest: "{{ocp_install_dir}}/{{cluster_name}}-{{ hostvars[item].host }}.nmconnection"
  with_items:
    - "{{ groups['bootstrap'] }}"
    - "{{ groups['masters'] }}"
    - "{{ groups['workers'] }}"

- name: Create customized ISO file for bootstrap
  shell: |
    coreos-installer iso customize \
      --dest-device {{iso_dest_device}} \
      --dest-ignition {{ocp_install_dir}}/bootstrap.ign \
      --dest-kargs-append ip={{item}}::{{default_gateway}}:255.255.255.0:{{ hostvars[item].host }}:ens192:none \
      --dest-kargs-append nameserver={{_dns_server}} \
      --network-keyfile {{ocp_install_dir}}/{{cluster_name}}-{{ hostvars[item].host }}.nmconnection \
      -o {{ocp_install_dir}}/{{cluster_name}}-{{ hostvars[item].host }}.iso \
      --force \
      {{ocp_install_dir}}/{{rhcos_iso_package}}
  with_items:
    - "{{ groups['bootstrap'] }}"

- name: Create customized ISO files for masters
  shell: |
    coreos-installer iso customize \
      --dest-device {{iso_dest_device}} \
      --dest-ignition {{ocp_install_dir}}/master.ign \
      --dest-kargs-append ip={{item}}::{{default_gateway}}:255.255.255.0:{{ hostvars[item].host }}:ens192:none \
      --dest-kargs-append nameserver={{_dns_server}} \
      --network-keyfile {{ocp_install_dir}}/{{cluster_name}}-{{ hostvars[item].host }}.nmconnection \
      -o {{ocp_install_dir}}/{{cluster_name}}-{{ hostvars[item].host }}.iso \
      --force \
      {{ocp_install_dir}}/{{rhcos_iso_package}}
  with_items:
    - "{{ groups['masters'] }}"

- name: Create customized ISO files for workers
  shell: |
    coreos-installer iso customize \
      --dest-device {{iso_dest_device}} \
      --dest-ignition {{ocp_install_dir}}/worker.ign \
      --dest-kargs-append ip={{item}}::{{default_gateway}}:255.255.255.0:{{ hostvars[item].host }}:ens192:none \
      --dest-kargs-append nameserver={{_dns_server}} \
      --network-keyfile {{ocp_install_dir}}/{{cluster_name}}-{{ hostvars[item].host }}.nmconnection \
      -o {{ocp_install_dir}}/{{cluster_name}}-{{ hostvars[item].host }}.iso \
      --force \
      {{ocp_install_dir}}/{{rhcos_iso_package}}
  with_items:
    - "{{ groups['workers'] }}"