---
# Get and format volumes, then mount to the appropriate directory

- name: Get volume for specified selector of {{ volume_selector }}
  shell: "lsblk -l | grep '{{ volume_selector }}' | head -1 | awk '{print $1}'"
  register: volume_name

- name: Format volume "/dev/{{ volume_name.stdout }}"
  filesystem:
    fstype: xfs
    dev: "/dev/{{ volume_name.stdout }}"
  when: volume_name.stdout != ""

- name: Mount volume "{{ mount_point }}"
  mount:
    path: "{{ mount_point }}"
    src: /dev/{{ volume_name.stdout }}
    fstype: xfs
    opts: noatime
    state: mounted
  when: volume_name.stdout != ""
