---
# This playbook prepares the environment to install OpenShift 4.x

- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - include: tasks/init_facts.yaml
    - include: tasks/check_variables.yaml
    - include: tasks/dns_reset.yaml
    - include: tasks/firewall_iptables_remove.yaml
    - include: tasks/set_hostname.yaml
    - include: tasks/hosts.yaml
      tags: hosts

- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  tasks:
    - include: tasks/ocp_install_dir.yaml

    - include: tasks/global_proxy.yaml
      tags: proxy

    - include: tasks/chrony_server.yaml
      tags: chrony
    - include: tasks/chrony_client.yaml
      tags: chrony

    - include: tasks/http_server.yaml
      tags: http
    - include: tasks/etc_ansible_hosts.yaml
    - include: tasks/ocp_download.yaml
      tags: download
      when: install_script_already_run==False

- name: Configure SSH
  import_playbook: tasks/ssh_playbook.yaml
  tags: ssh
 
- hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  tasks:
    - include: tasks/dnsmasq_libvirt_remove.yaml

    - name:
      block:
      - include: tasks/tftpboot.yaml
        tags: tftp
      - include: tasks/pxe_links.yaml
      when: rhcos_installation_method|upper=="PXE"

    - include: tasks/dns_server.yaml
      tags: dns
    - include: tasks/dns_interface.yaml
      tags: dns

    - name: 
      block: 
      - include: tasks/ocp_install_config.yaml
        tags: ocp_install_config
      - include: tasks/ocp_ignition.yaml
        tags: ignition
      - include: tasks/create_oauth.yaml
      when: install_script_already_run==False

    - include: tasks/registry_storage.yaml
    - include: tasks/ocp_install_scripts.yaml
      tags: scripts

- hosts: lb
  remote_user: root
  gather_facts: yes
  become: yes
  tasks:
    - include: tasks/haproxy.yaml
      tags: haproxy
      when: manage_load_balancer is not defined or manage_load_balancer|bool

- hosts:
    - nfs
  remote_user: root
  gather_facts: no
  become: yes

  tasks:
    - name: Prepare NFS volume
      include: tasks/prepare_xfs_volume.yaml
      vars:
        volume_selector: "{{ nfs_volume_selector }}"
        mount_point: "{{ nfs_volume_mount_path }}"
      when: manage_nfs|bool
    - name: Configure NFS server
      include: tasks/nfs_server.yaml
      when: manage_nfs|bool

- hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  tasks:
    - include: tasks/ocp_install_execute.yaml
      when: run_install is defined and run_install|bool and install_script_already_run==False and rhcos_installation_method|upper!="IPI"
